name: Test package

# on:
#   pull_request:
#   push:
#     branches: [main]
on: [push]

jobs:
  test-code:
    name: Test installation
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Clone repos
        run: |
          mkdir clones
          git clone --single-branch --branch main https://github.com/rakshakonanur/rk-sscp25-deep-learning-cardiac-mechanics.git clones/rk-sscp25
          git clone --single-branch --branch main https://github.com/annaqi13/sscp25.git clones/sscp25
          cd clones/sscp25 && git checkout e216f9268033ebd05afb8dda06d7b83f86a67fd7 && cd ../..
          git clone --single-branch --branch main https://github.com/UOA-Heart-Mechanics-Research/biv-me.git clones/biv-me@v1.1.5
          git clone --single-branch --branch main https://github.com/rakshakonanur/rk-ukb-atlas.git clones/rk-ukb-atlas
          git clone --single-branch --branch main https://github.com/rakshakonanur/fenicsx-pulse.git clones/fenicsx-pulse


      - name: Download atlas and cohort data
        run: |
          mkdir refs
          curl -L "https://drive.usercontent.google.com/download?id=1nGlaEU_l6eJrSsk2DGX7Uqq0DgcDJU31&confirm=xxx" -o refs/BioBank_EDES_200.mat


      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-py-${{ matrix.python-version }}${{
            hashFiles('clones/rk-sscp25/environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: false
          channels: conda-forge
          activate-environment: sscp25-deep-learning-cardiac-mechanics
          environment-file: clones/rk-sscp25/environment.yml

      




      - name: Install development version of scifem
        if : ${{ matrix.container == 'ghcr.io/fenics/dolfinx/dolfinx:nightly' }}
        run: |
          python3 -m pip install git+https://github.com/scientificcomputing/scifem.git --no-build-isolation

      - name: Install package
        run: |
          python3 -m pip install scifem --no-build-isolation
          python3 -m pip install .[test]

      - name: Run tests
        run: python3 -m pytest -m "not benchmark"

      - name: Extract Coverage
        run: |
          python3 -m coverage report | sed 's/^/    /' >> $GITHUB_STEP_SUMMARY
          python3 -m coverage json
          export TOTAL=$(python3 -c "import json;print(json.load(open('coverage.json'))['totals']['percent_covered_display'])")
          echo "total=$TOTAL" >> $GITHUB_ENV

      - name: Upload HTML report.
        if: ${{ matrix.container == 'ghcr.io/fenics/dolfinx/dolfinx:v0.9.0' }}
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: htmlcov
